### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by enumag** [labrador-kennel/http-cors#4]
Okay I finally started using this package so I'd like to give you some feedback.

Bugs
----

Firstly, there is a critical bug that it doesn't work with origin `'*'`. See https://github.com/labrador-kennel/http-cors/pull/3 for a fix.

Next there is a bug where [headers comparison](https://github.com/labrador-kennel/http-cors/blob/363822d04d12e66f025c24a3365a8e3e5cf143f4/src/CorsMiddleware.php#L61) failed on case sensitivity. I recommend changing all headers to lowercase before comparing them.

Next the readme is wrong since `ArrayConfiguration::getMaxAge()` will fail because the `max_age` index doesn't exist in the array. Also it's not clear what to set when I "don't care" and wanna use whatever the browser uses by default. I recommend changing `getMaxAge` to return `?int` and not add the header at all if null is used.

Improvements
----

I very much dislike the ArrayConfiguration in general since there is no type checking when creating it. I'd recommend deprecating / removing it completely in favor of a builder. See [this](https://github.com/prooph/event-store-client/blob/master/src/ConnectionSettingsBuilder.php) and [this](https://github.com/prooph/event-store-client/blob/master/src/ConnectionSettings.php) for how I think it should work. This would make the configuration more object-like, with IDE suggestions, type safety etc.

Finally there is no way to have different configuration for different paths. I don't need it personally but ideally the cors middleware should call something that would return a configuration based on regex matching.

----

I don't have time to work on all of these at the moment, just wanted to give you my feedback and recommendations what I think could be improved.

**Comment by cspray** [comment]
These improvements sound good and makes sense to me. I agree the ArrayConfiguration isn't ideal. I am going to have some time to work on personal projects more next week and I can take a look at making some of the improvements around the configuration.

**Comment by cspray** [comment]
@enumag If I haven't explicitly said so already thank you for taking the time to use my project and contribute back to it! I've taken the suggestions that you have made and created a new GitHub Project with [tasks to push to an 0.3 release](https://github.com/labrador-kennel/http-cors/projects/1). I'm not entirely sure yet if the regex based Configuration would make it into this version but it is definitely something that I want to implement.

As always I'd welcome additional PRs that helped complete these tasks. If you do decide to work on a task please assign yourself to it so we can minimize potential work overlap. I will be taking on the Configuration builder this weekend. I would love to get your feedback as the Configuration builder is implemented.

Since all of the suggestion made here are part of the 0.3.0 release or have been merged into the codebase I'm going to close this issue to keep things tidy. If you have any questions or feedback about a specific suggestion please post it in the respective issue.

Thanks!
